
## Step 3: Exploratory Data Analysis (EDA)
Analyze trends, volatility, outliers, seasonality, and compute key metrics.

In [1]:
import sys, os
import pandas as pd
sys.path.append(os.path.abspath('..'))

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
from src.eda import EDA

In [5]:
cleaned_data = pd.read_csv('../data/cleaned_data.csv')

In [6]:
# Initialize EDA
eda = EDA(cleaned_data)

In [7]:
# Calculate daily returns
eda.calculate_daily_returns()

,Date,Ticker,Close,High,Low,Open,Volume,Daily_Return
0,2015-01-02,BND,62.573112,62.603397,62.398980,62.406553,2218800,NaN
1,2015-01-02,SPY,172.592880,173.811114,171.542687,173.391037,121465900,NaN
2,2015-01-02,TSLA,14.620667,14.883333,14.217333,14.858000,71466000,NaN
3,2015-01-05,BND,62.754848,62.777560,62.611000,62.641284,5820100,0.002904
4,2015-01-05,SPY,169.475906,171.702310,169.165053,171.534282,169632600,-0.018060
...,...,...,...,...,...,...,...,...
7600,2025-01-29,SPY,601.809998,604.130005,599.219971,603.719971,37177400,-0.004483
7601,2025-01-29,TSLA,389.100006,398.589996,384.480011,395.209991,68033600,-0.022583
7602,2025-01-30,BND,72.204674,72.294378,72.144864,72.224605,5622300,0.001382
7603,2025-01-30,SPY,605.039978,606.599976,600.719971,603.960022,39281300,0.005367
7604,2025-01-30,TSLA,400.279999,412.500000,384.410004,410.779999,98092900,0.028733

In [8]:
tickers = ['TSLA', 'BND', 'SPY']


### Visualize Closing Prices
Plot closing prices for each ticker to identify trends.

In [9]:
# Plot closing prices
for ticker in tickers:
    eda.plot_closing_price(ticker)

### Analyze Volatility
Calculate rolling means and standard deviations (20-day window).

In [10]:
eda.analyze_volatility(window=20)

,Date,Ticker,Close,High,Low,Open,Volume,Daily_Return,Rolling_Mean,Rolling_Std
0,2015-01-02,BND,62.573112,62.603397,62.398980,62.406553,2218800,NaN,NaN,NaN
1,2015-01-02,SPY,172.592880,173.811114,171.542687,173.391037,121465900,NaN,NaN,NaN
2,2015-01-02,TSLA,14.620667,14.883333,14.217333,14.858000,71466000,NaN,NaN,NaN
3,2015-01-05,BND,62.754848,62.777560,62.611000,62.641284,5820100,0.002904,NaN,NaN
4,2015-01-05,SPY,169.475906,171.702310,169.165053,171.534282,169632600,-0.018060,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
7600,2025-01-29,SPY,601.809998,604.130005,599.219971,603.719971,37177400,-0.004483,0.000608,0.009125
7601,2025-01-29,TSLA,389.100006,398.589996,384.480011,395.209991,68033600,-0.022583,-0.004567,0.036204
7602,2025-01-30,BND,72.204674,72.294378,72.144864,72.224605,5622300,0.001382,0.000288,0.002925
7603,2025-01-30,SPY,605.039978,606.599976,600.719971,603.960022,39281300,0.005367,0.001447,0.008724
7604,2025-01-30,TSLA,400.279999,412.500000,384.410004,410.779999,98092900,0.028733,-0.001480,0.036283

In [11]:
# Display updated data with volatility metrics
eda.data.head()

,Date,Ticker,Close,High,Low,Open,Volume,Daily_Return,Rolling_Mean,Rolling_Std
0,2015-01-02,BND,62.573112,62.603397,62.398980,62.406553,2218800,NaN,NaN,NaN
1,2015-01-02,SPY,172.592880,173.811114,171.542687,173.391037,121465900,NaN,NaN,NaN
2,2015-01-02,TSLA,14.620667,14.883333,14.217333,14.858000,71466000,NaN,NaN,NaN
3,2015-01-05,BND,62.754848,62.777560,62.611000,62.641284,5820100,0.002904,NaN,NaN
4,2015-01-05,SPY,169.475906,171.702310,169.165053,171.534282,169632600,-0.018060,NaN,NaN

In [12]:
# Detect outliers
outliers = eda.detect_outliers(threshold=3)
outliers

,Date,Ticker,Close,High,Low,Open,Volume,Daily_Return,Rolling_Mean,Rolling_Std,Z_Score
638,2015-11-04,TSLA,15.442000,15.516000,15.013333,15.133333,190896000,0.111735,0.000521,0.035790,3.107441
696,2015-12-03,BND,62.492912,62.833602,62.469685,62.833602,2510600,-0.007745,-0.000302,0.002323,3.204572
1112,2016-06-22,TSLA,13.110667,13.730000,13.050000,13.298000,356136000,-0.104503,-0.004643,0.031008,3.220503
1117,2016-06-24,SPY,176.086334,182.679609,175.635805,176.424228,333444400,-0.035909,-0.001174,0.009589,3.622553
1262,2016-09-01,TSLA,13.384667,14.073333,13.366667,13.934000,119146500,-0.053016,-0.006806,0.014229,3.247559
1276,2016-09-09,SPY,184.784958,188.033943,184.758967,187.981962,221589100,-0.023935,-0.001225,0.006040,3.759710
1399,2016-11-07,SPY,185.605194,185.640032,181.599648,181.599648,109794900,0.022057,-0.000679,0.006773,3.356730
1404,2016-11-09,BND,65.038177,65.442192,64.974801,65.355052,3448800,-0.009888,-0.000648,0.002585,3.575219
1792,2017-05-17,SPY,207.454514,211.202097,207.392927,211.202097,172174100,-0.017744,0.000523,0.005683,3.214151
1969,2017-08-10,SPY,215.485199,217.854341,215.432161,217.721732,120479500,-0.014115,-0.000128,0.003850,3.633223
2335,2018-02-05,SPY,235.672043,246.315827,235.118428,244.172791,294681800,-0.041823,-0.001695,0.012039,3.333114
2345,2018-02-08,TSLA,21.015333,23.241333,20.973333,22.887333,154719000,-0.086290,-0.002669,0.026268,3.183382
2588,2018-06-06,TSLA,21.299999,21.478001,19.832001,20.033333,281509500,0.097448,0.003245,0.030160,3.123446
2708,2018-08-02,TSLA,23.302668,23.332666,21.544001,21.896000,348225000,0.161880,0.006969,0.042823,3.617501
2851,2018-10-10,SPY,251.753525,259.542249,251.373603,259.469865,214731000,-0.031663,-0.001648,0.008092,3.709007
3443,2019-07-25,TSLA,15.254667,15.633333,15.036667,15.566667,336274500,-0.136137,0.002828,0.036985,3.757321
3463,2019-08-05,SPY,260.645416,264.676948,258.716881,264.566750,178745400,-0.030073,-0.002202,0.008482,3.285899
3635,2019-10-24,TSLA,19.978666,20.328667,19.280001,19.891333,445813500,0.176692,0.011411,0.042404,3.897728
3839,2020-02-03,TSLA,52.000000,52.409332,44.901333,44.912666,705975000,0.198949,0.030002,0.054709,3.088079
3912,2020-03-10,BND,75.536789,76.496379,75.536789,76.278292,14177600,-0.013444,0.000842,0.004266,3.348410
3915,2020-03-11,BND,74.106148,76.103831,74.036365,75.702550,10511600,-0.018940,-0.000023,0.006139,3.081409
3918,2020-03-12,BND,70.075920,74.053836,66.726091,72.823826,16986900,-0.054385,-0.002684,0.013627,3.793950
4108,2020-06-11,SPY,280.341736,291.103674,279.782213,290.460194,209243600,-0.057649,0.003429,0.018036,3.386414
4285,2020-09-03,SPY,323.519989,333.814095,320.897267,333.336379,148011100,-0.034414,0.001680,0.010338,3.491510
4413,2020-11-04,BND,78.035545,78.088678,77.920438,77.982420,5667400,0.006855,0.000293,0.002067,3.174144
4641,2021-02-25,BND,75.933968,76.343946,75.684420,76.290466,9956100,-0.008726,-0.001289,0.002407,3.089746
4667,2021-03-09,TSLA,224.526672,226.029999,198.403336,202.726669,202569900,0.196412,-0.010591,0.062441,3.315209
5147,2021-10-25,TSLA,341.619995,348.339996,314.733337,316.843323,188556300,0.126616,0.013411,0.029951,3.779631
5215,2021-11-26,SPY,437.709137,442.410758,436.564713,440.923024,112669600,-0.022303,0.000091,0.006403,3.497598
5937,2022-11-10,BND,66.281548,66.281548,65.725262,65.734536,7014100,0.020702,0.000861,0.006357,3.121021
6842,2024-01-25,TSLA,182.630005,193.000000,180.059998,189.699997,198076800,-0.121253,-0.016422,0.029463,3.558040
7028,2024-04-24,TSLA,162.130005,167.970001,157.509995,162.839996,181178000,0.120611,-0.003826,0.040097,3.103384
7409,2024-10-24,TSLA,260.480011,262.119995,242.649994,244.679993,204491900,0.219190,0.002652,0.057485,3.766884
7522,2024-12-18,SPY,584.313416,604.375836,583.924709,601.953994,108248700,-0.029803,-0.000311,0.008005,3.684425

### Decompose Time Series
Decompose each ticker's closing price into trend, seasonal, and residual components (annual period = 252 trading days).

In [13]:
for ticker in tickers:
    eda.decompose_series(ticker, period=252)

### Calculate Key Metrics
Compute VaR (95%) and Sharpe Ratio for each ticker (assume 2% risk-free rate).

In [14]:
metrics = eda.calculate_metrics(risk_free_rate=0.02)
metrics

{'BND': {'VaR (95%)': np.float64(-0.004801219479811536),
  'Sharpe Ratio': np.float64(-0.07866243387466695)},
 'SPY': {'VaR (95%)': np.float64(-0.01671924939688598),
  'Sharpe Ratio': np.float64(0.6838425788060678)},
 'TSLA': {'VaR (95%)': np.float64(-0.05138725064469325),
  'Sharpe Ratio': np.float64(0.825698921799305)}}

## Summary
Check the `logs/` directory for detailed logs and `notebooks/` for saved plots. Key insights:
- Trends: See closing price plots.
- Volatility: Rolling stats added to data.
- Outliers: Listed above.
- Seasonality: Decomposition plots saved.
- Metrics: VaR and Sharpe Ratio computed.